DROP TABLE IF EXISTS cposts;

CREATE TABLE cposts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    cover TEXT NOT NULL
);